In [1]:
import torch

In [2]:
### Questions

In [3]:
# Make a 1D tensor with values [10, 20, 30, 40]. Print its shape and dtype.
oneD=torch.tensor([10,20,30,40])
print(oneD.shape)
print(oneD.dtype)

torch.Size([4])
torch.int64


In [4]:
# Create a 3x3 tensor of all zeros, and a 3x3 tensor of all ones. Add them together and print the result.
zeros_tensor=torch.zeros(3,3)
ones_tensor=torch.ones(3,3)
print(f"Zeros Tensor :{zeros_tensor}")
print(f"Ones Tensor :{ones_tensor}")
print(f"Zeros Tensor + Ones Tensor :{zeros_tensor+ones_tensor}")

Zeros Tensor :tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Ones Tensor :tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor + Ones Tensor :tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [5]:
#Given t = torch.tensor([5, 10, 15, 20, 25]), print the first element, the last element, and the elements from index 1 to 3.
t = torch.tensor([5, 10, 15, 20, 25])
print(f"First Element: {t[0]}")
print(f"Last Element: {t[-1]}")
print(f"Elements from index 1 to 3: {t[1:4]}")

First Element: 5
Last Element: 25
Elements from index 1 to 3: tensor([10, 15, 20])


In [6]:
#Create a tensor with values 0 to 11 using torch.arange(12), then reshape it into a 3x4 tensor.
a = torch.arange(12).reshape(3, 4)
print(a)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [7]:
#Sum, Difference, Element-wise Product
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
print(a + b)
print(a - b)
print(a * b)

tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[ 5, 12],
        [21, 32]])


In [8]:
#2×3 Ones → Multiply by 5 → Add 2
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

print(a + b)
print(a - b)
print(a * b)

tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[ 5, 12],
        [21, 32]])


In [9]:
#Maximum, Minimum, Average
t=torch.tensor([4, 8, 15, 16, 23, 42])
print(t.max())
print(t.min())
print(t.float().mean())

tensor(42)
tensor(4)
tensor(18.)


In [10]:
#Random Tensor → NumPy Array
a = torch.rand(2, 2)
b = a.numpy()

print(a)
print(b)

tensor([[0.2548, 0.0075],
        [0.8969, 0.6605]])
[[0.2547577  0.00748086]
 [0.89685607 0.6605258 ]]


In [11]:
#Transpose a 2×3 Tensor
a = torch.tensor([[1, 2, 3], [4, 5, 6]])

print(a.T)
print(a.T.shape)

tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2])


In [12]:
#Print dtype
t = torch.tensor([1.5, 2.5, 3.5])

print(t.dtype)

torch.float32


In [13]:
#4×4 Identity Matrix
a = torch.eye(4)

print(a)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [14]:
#Manual Seed
torch.manual_seed(0)
a = torch.rand(2, 2)
print(a)

torch.manual_seed(0)
b = torch.rand(2, 2)
print(b)

print(torch.equal(a, b))

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])
tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])
True


In [15]:
#Element in Row 1, Column 2
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(a[1, 2])

tensor(6)


In [16]:
#Second Row and Third Column
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(a[1, :])
print(a[:, 2])

tensor([4, 5, 6])
tensor([3, 6, 9])


In [17]:
#Change Center Element to 99
a = torch.ones(3, 3)
a[1, 1] = 99

print(a)

tensor([[ 1.,  1.,  1.],
        [ 1., 99.,  1.],
        [ 1.,  1.,  1.]])


In [18]:
#Concatenate Along Rows (dim=0)
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

c = torch.cat((a, b), dim=0)

print(c)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [19]:
#Concatenate Along Columns (dim=1)
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

c = torch.cat((a, b), dim=1)

print(c)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [20]:
#2×3 Tensor Filled With 7
a = torch.full((2, 3), 7)

print(a)

tensor([[7, 7, 7],
        [7, 7, 7]])


In [21]:
#Sum of All Elements
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(a.sum())

tensor(45)


In [22]:
#21. Sum of each row and each column in a 2x3 tensor
t = torch.tensor([[1, 2, 3], [4, 5, 6]])
row_sums = t.sum(dim=1)
column_sums = t.sum(dim=0)
print(f"Sum of each row: {row_sums}")
print(f"Sum of each column: {column_sums}")

Sum of each row: tensor([ 6, 15])
Sum of each column: tensor([5, 7, 9])


In [23]:
# 22. Square every element in [1, 2, 3, 4]
t = torch.tensor([1, 2, 3, 4])
squared = t ** 2
print(squared)

tensor([ 1,  4,  9, 16])


In [24]:
#  23. Compute the square root of each element in [4, 9, 16, 25]
t = torch.tensor([4, 9, 16, 25])
square_roots = torch.sqrt(t.float())
print(square_roots)

tensor([2., 3., 4., 5.])


In [25]:
# 24.Element-wise equality check for two tensors of the same shape
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[1, 0], [3, 4]])
print(a == b)

tensor([[ True, False],
        [ True,  True]])


In [26]:
# 25. Count the elements greater than 4
t = torch.tensor([2, 5, 8, 1, 9, 3])
count = (t > 4).sum()
print(count)

tensor(3)


In [27]:
# 26. Flatten a 2x3 tensor into a 1D tensor
t = torch.tensor([[1, 2, 3], [4, 5, 6]])
flattened = t.flatten()
print(flattened)
print(flattened.shape)

tensor([1, 2, 3, 4, 5, 6])
torch.Size([6])


In [28]:
# 27. Add an extra dimension to make the shape (1, 5)
t = torch.tensor([1, 2, 3, 4, 5])
t_with_extra_dimension = t.unsqueeze(0)
print(t_with_extra_dimension)
print(t_with_extra_dimension.shape)

tensor([[1, 2, 3, 4, 5]])
torch.Size([1, 5])


In [29]:
# 28. Remove the extra dimension from a tensor of shape (1, 4)
t = torch.tensor([[1, 2, 3, 4]])
t_without_extra_dimension = t.squeeze(0)
print(t_without_extra_dimension)
print(t_without_extra_dimension.shape)

tensor([1, 2, 3, 4])
torch.Size([4])


In [30]:
# 29. Clone a tensor and confirm the clone is unaffected by changes to the original
original = torch.tensor([1, 2, 3])
clone = original.clone()
original[0] = 99
print(f"Original: {original}")
print(f"Clone: {clone}")

Original: tensor([99,  2,  3])
Clone: tensor([1, 2, 3])


In [31]:
# 30. Assign a tensor to another variable and confirm both refer to the same data
original = torch.tensor([1, 2, 3])
new_variable = original
original[0] = 99
print(f"Original: {original}")
print(f"New variable: {new_variable}")

Original: tensor([99,  2,  3])
New variable: tensor([99,  2,  3])


In [32]:
# 31. Convert an integer tensor to a float tensor
integer_tensor = torch.tensor([1, 2, 3])
float_tensor = integer_tensor.float()
print(float_tensor)
print(float_tensor.dtype)

tensor([1., 2., 3.])
torch.float32


In [33]:
# 32. Compute absolute values using torch.abs
t = torch.tensor([-3, -1, 0, 2, 4])
absolute_values = torch.abs(t)
print(absolute_values)

tensor([3, 1, 0, 2, 4])


In [34]:
# 33. Round each value using torch.round
t = torch.tensor([1.2, 2.7, 3.5, 4.1])
rounded = torch.round(t)
print(rounded)

tensor([1., 3., 4., 4.])


In [35]:
#34. Sort a tensor in ascending order
t = torch.tensor([5, 2, 8, 1, 9])
ascending = torch.sort(t).values
print(ascending)

tensor([1, 2, 5, 8, 9])


In [36]:
# 35. Sort the tensor in descending order
t = torch.tensor([5, 2, 8, 1, 9])
descending = torch.sort(t, descending=True).values
print(descending)

tensor([9, 8, 5, 2, 1])


In [37]:
# 36.Repeat [1, 2, 3] three times
t = torch.tensor([1, 2, 3])
repeated = t.repeat(3)
print(repeated)

tensor([1, 2, 3, 1, 2, 3, 1, 2, 3])


In [38]:
# 37. Check whether two identical 2x2 tensors are fully equal
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[1, 2], [3, 4]])
print(torch.equal(a, b))

True


In [39]:
# 38. Fill every element of a 2x2 tensor with 9
t = torch.zeros(2, 2)
t.fill_(9)
print(t)

tensor([[9., 9.],
        [9., 9.]])


In [40]:
# 39.Check whether a tensor is on CPU or CUDA
t = torch.tensor([1, 2, 3])
print(f"Tensor device: {t.device}")
print("CUDA" if t.device.type == "cuda" else "CPU")

Tensor device: cpu
CPU


In [41]:
#40.Compute 2*a + 3*b
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
result = 2 * a + 3 * b
print(result)

tensor([14, 19, 24])
