In [1]:
import torch

In [2]:
#Directly from data
data=[[1,2], [3,4]]
x_data=torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [3]:
#From numpy array
import numpy as np
np_array=np.array(data)
x_np=torch.from_numpy(np_array)

In [4]:
#From other tesnors
x_ones=torch.ones_like(x_data) #retains the properties of x_data
print(f"Ones Tensor :\n {x_ones}\n")
x_rand=torch.rand_like(x_data, dtype=torch.float) #overrides the datatype of x_data
print(f"Random Tensor :\n {x_rand}\n")

Ones Tensor :
 tensor([[1, 1],
        [1, 1]])

Random Tensor :
 tensor([[0.6134, 0.8203],
        [0.6655, 0.2700]])



In [5]:
#populating tensors with random/constant values
shape=(2,3,) #tuple of tensor dimensions
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)
torch.manual_seed(1789)
rand_tensor=torch.rand(shape)
empty_tensor=torch.empty(shape) #memory is allocated, tensor populated with gardbage
print(f"Ones Tensor :\n {ones_tensor}\n")
print(f"Zeros Tensor :\n {zeros_tensor}\n")
print(f"Random Tensor :\n {rand_tensor}\n")
print(f"Empty Tensor :\n {empty_tensor}\n")

Ones Tensor :
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor :
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Random Tensor :
 tensor([[0.9631, 0.4014, 0.7564],
        [0.5782, 0.5438, 0.1929]])

Empty Tensor :
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [6]:
x=torch.empty(2,2,3)
print(x.shape,"\n")
print(x)

torch.Size([2, 2, 3]) 

tensor([[[2.7689e-21, 0.0000e+00, 5.5291e-21],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 1.4013e-45],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [7]:
a=torch.ones((2,3), dtype=torch.int16)
print(a.dtype)
a=torch.ones((2,3), dtype=torch.float64)
print(a.dtype)
a=torch.ones((2,3), dtype=torch.int8)
print(a.dtype)
a=torch.ones((2,3), dtype=torch.int32)
print(a.dtype)
a=torch.ones((2,3), dtype=torch.int64)
print(a.dtype)
a=torch.ones((2,3), dtype=torch.bool)
print(a.dtype)

torch.int16
torch.float64
torch.int8
torch.int32
torch.int64
torch.bool


In [8]:
#Create a tesnor
tensor=torch.rand(3,2)
print(f"Device tensor is initially stored on : {tensor.device}")

Device tensor is initially stored on : cpu


In [9]:
#Check if GPU is available and move tensor to GPU if it is
if torch.cuda.is_available():
  tensor=tensor.to("cuda")
  print(f"Device tensor is now stored on : {tensor.device}")
else:
  print(f"CUDA is not available. Tensor remains on CPU")

CUDA is not available. Tensor remains on CPU


In [10]:
tensor=torch.ones(4,4)
print(f"First row: {tensor[0]}","\n")
print(f"First column: {tensor[:,0]}","\n")
print(f"Last column: {tensor[...,-1]}","\n")
tensor[:,1]=0
print(tensor)

First row: tensor([1., 1., 1., 1.]) 

First column: tensor([1., 1., 1., 1.]) 

Last column: tensor([1., 1., 1., 1.]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [11]:
ones=torch.ones(2,2)+1
twos=torch.ones(2,2)*2
threes=(torch.ones(2,2)*7-1)/2
fours=torch.tensor([[10.,20.],[30.,40.]])
print(ones)
print(twos)
print(threes)
print(fours)

tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[10., 20.],
        [30., 40.]])


In [12]:
powers2=twos**torch.tensor([[1,2],[3,4]])
print(powers2)
fives=ones+fours
print(fives)
dozens=threes*fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[12., 22.],
        [32., 42.]])
tensor([[ 30.,  60.],
        [ 90., 120.]])


In [13]:
rand=torch.rand(2,4)
doubled=rand*(torch.ones(1,4)*2)
print(rand)
print(doubled)

tensor([[0.2569, 0.8153, 0.3774, 0.6209],
        [0.8973, 0.6783, 0.8594, 0.6721]])
tensor([[0.5138, 1.6306, 0.7549, 1.2419],
        [1.7946, 1.3567, 1.7187, 1.3442]])


In [14]:
a=torch.ones(4,3,2)
b=a*torch.rand(3,2)
print(b,"\n")
c=a*torch.rand(4,1,2)
print(c, "\n")

tensor([[[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]],

        [[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]],

        [[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]],

        [[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]]]) 

tensor([[[0.4606, 0.7056],
         [0.4606, 0.7056],
         [0.4606, 0.7056]],

        [[0.5921, 0.0557],
         [0.5921, 0.0557],
         [0.5921, 0.0557]],

        [[0.3866, 0.2989],
         [0.3866, 0.2989],
         [0.3866, 0.2989]],

        [[0.8993, 0.2320],
         [0.8993, 0.2320],
         [0.8993, 0.2320]]]) 



In [15]:
import math

a=torch.rand(2,4)*2-1
print(torch.abs(a),"\n")
print(torch.ceil(a), "n")
print(torch.floor(a),"\n")
print(torch.clamp(a,-0.5,0.5))

tensor([[0.5100, 0.6088, 0.6300, 0.7952],
        [0.4373, 0.5769, 0.8933, 0.1511]]) 

tensor([[-0., -0., 1., -0.],
        [-0., 1., -0., -0.]]) n
tensor([[-1., -1.,  0., -1.],
        [-1.,  0., -1., -1.]]) 

tensor([[-0.5000, -0.5000,  0.5000, -0.5000],
        [-0.4373,  0.5000, -0.5000, -0.1511]])


In [16]:
angles=torch.tensor([0, math.pi/4, math.pi/2, 3*math.pi/4])
sines=torch.sin(angles)
inverses=torch.asin(sines)
print(f"Angles : {angles}")
print(f"Sine values : {sines}")
print(f"Cosine values : {sines}")


Angles : tensor([0.0000, 0.7854, 1.5708, 2.3562])
Sine values : tensor([0.0000, 0.7071, 1.0000, 0.7071])
Cosine values : tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [17]:
b=torch.tensor([1,5,11])
c=torch.tensor([2,7,10])
print(torch.bitwise_xor(b,c))

tensor([3, 2, 1])


In [18]:
#Elements Greater Than 3
t = torch.tensor([1, 2, 3, 4, 5])

print(t > 3)

tensor([False, False, False,  True,  True])


In [19]:
print('/nBroadcasted, element-wise equality comparison:')
d=torch.tensor([[1., 2.],[3.,4.]])
print(d,"\n")
e=torch.ones(1,2)
print(e)

/nBroadcasted, element-wise equality comparison:
tensor([[1., 2.],
        [3., 4.]]) 

tensor([[1., 1.]])


In [20]:
d=torch.tensor([[1., 2.], [3., 4.]])
print(torch.max(d))
print(torch.max(d).item())
print(torch.mean(d))
print(torch.std(d))
print(torch.prod(d))
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2])))

tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


In [21]:
v1=torch.tensor([1.,0.,0.])
v2=torch.tensor([0.,1.,0.])
print(torch.cross(v2,v1),"\n")

m1=torch.rand(2,2)
m2=torch.tensor([[3., 0], [0., 3]])
print(m1,"]\n")
m3=torch.matmul(m1,m2)
print(m3, "\n")
print(torch.svd(m3),"\n")

tensor([ 0.,  0., -1.]) 

tensor([[0.1490, 0.2725],
        [0.6428, 0.3502]]) ]

tensor([[0.4469, 0.8176],
        [1.9285, 1.0507]]) 

torch.return_types.svd(
U=tensor([[-0.3505, -0.9366],
        [-0.9366,  0.3505]]),
S=tensor([2.3382, 0.4736]),
V=tensor([[-0.8395,  0.5434],
        [-0.5434, -0.8395]])) 



/tmp/ipykernel_1633/2387409787.py:3: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at /pytorch/aten/src/ATen/native/Cross.cpp:63.)
  print(torch.cross(v2,v1),"\n")


In [22]:
a=torch.tensor([0, math.pi/4, math.pi/2, 3*math.pi/4])
print('a:')
print(a)
print(torch.sin(a))
print(a)

b=torch.tensor([0, math.pi/4, math.pi/2, 3*math.pi/4])
print('b:')
print(b)
print(torch.cos(b))
print(b)
print(torch.sin_(b))
print(b)

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])
b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([ 1.0000e+00,  7.0711e-01, -4.3711e-08, -7.0711e-01])
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [23]:
a = torch.ones(2,1)
b = torch.rand(2,2)

print("Before:")
print(a)
print(b)

print("\nAfter adding")
print(a.add_(a))
print(a)
print(b)

print("\nAfter adding :")
a = a + b
print(a)
print(b)

print("\nAfter multiplying :")
print(b.mul_(b))
print(a)

Before:
tensor([[1.],
        [1.]])
tensor([[0.8198, 0.1592],
        [0.0902, 0.7986]])

After adding
tensor([[2.],
        [2.]])
tensor([[2.],
        [2.]])
tensor([[0.8198, 0.1592],
        [0.0902, 0.7986]])

After adding :
tensor([[2.8198, 2.1592],
        [2.0902, 2.7986]])
tensor([[0.8198, 0.1592],
        [0.0902, 0.7986]])

After multiplying :
tensor([[0.6721, 0.0253],
        [0.0081, 0.6378]])
tensor([[2.8198, 2.1592],
        [2.0902, 2.7986]])


In [24]:
### 5 Questions :

In [25]:
#1. Obtain a tensor containing only zeroes from the given tesnor

pattern=torch.tensor([
    [1,1,1,1],
    [1,0,0,1],
    [1,0,0,1],
    [1,1,1,1]
])
pattern_zero=torch.zeros_like(pattern)
print(pattern_zero)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


In [26]:
#2. Create a Numpy array of shape(1,3,3) using PyTorch
numpy_array=torch.rand(1,3,3)
print(numpy_array)

tensor([[[0.4120, 0.8499, 0.5300],
         [0.3159, 0.7081, 0.1727],
         [0.9051, 0.5988, 0.2455]]])


In [27]:
#3. Create two random(2,2,2) tesnors and find the max, min, mean std of their product(matrix multiplication)
a=torch.rand(2,2,2)
b=torch.rand(2,2,2)
c=torch.matmul(a,b)
print(c)
print(f"Max :{c.max()}")
print(f"Min :{c.min()}")
print(f"Mean:{c.mean()}")
print(f"Std :{c.std()}")

tensor([[[0.1074, 0.0613],
         [0.1669, 0.0996]],

        [[0.8673, 0.7235],
         [0.9453, 0.7556]]])
Max :0.9452829957008362
Min :0.06132383644580841
Mean:0.4658515155315399
Std :0.3885912001132965


In [28]:
#4. Convert a 16x16 tensor into 1x256 tensor
a=torch.rand(16,16)
b=torch.reshape(a,(1,256))
print(a)
print(b)

tensor([[0.4608, 0.6367, 0.6119, 0.7810, 0.3536, 0.8651, 0.0816, 0.7734, 0.5292,
         0.3624, 0.9631, 0.4195, 0.7474, 0.9986, 0.9005, 0.1822],
        [0.4105, 0.3284, 0.9011, 0.3572, 0.3448, 0.6483, 0.0641, 0.3240, 0.9911,
         0.7152, 0.5599, 0.9312, 0.6157, 0.2850, 0.9651, 0.0084],
        [0.6758, 0.6096, 0.0661, 0.7590, 0.7685, 0.9174, 0.6863, 0.6148, 0.8652,
         0.0989, 0.9946, 0.0064, 0.5736, 0.3399, 0.2148, 0.4567],
        [0.4887, 0.4287, 0.6620, 0.0410, 0.4947, 0.4832, 0.0296, 0.9237, 0.4310,
         0.9974, 0.2973, 0.9183, 0.2423, 0.1369, 0.7222, 0.4991],
        [0.6913, 0.2259, 0.7105, 0.6875, 0.7053, 0.9482, 0.6266, 0.4144, 0.4358,
         0.8737, 0.3486, 0.1296, 0.3094, 0.9082, 0.0822, 0.5552],
        [0.6057, 0.1233, 0.8049, 0.3587, 0.0135, 0.1651, 0.1482, 0.8680, 0.0246,
         0.3889, 0.4033, 0.4086, 0.0129, 0.4722, 0.5735, 0.6007],
        [0.5485, 0.5868, 0.3942, 0.5936, 0.4024, 0.0911, 0.0035, 0.2118, 0.5679,
         0.5858, 0.9733, 0.3692, 0.11

In [29]:
#5. Given two tensors x and y, find the coefficients that best model the linear relationship Y=ax+b (Linear Regression)
x = torch.tensor([1., 2., 3., 4., 5.])
y = torch.tensor([2., 4., 6., 8., 10.])

x_mean = x.mean()
y_mean = y.mean()

a = ((x - x_mean) * (y - y_mean)).sum() / ((x - x_mean) ** 2).sum()
b = y_mean - a * x_mean

print(a, b)

tensor(2.) tensor(0.)
